### ISSUE TITLE
请问是什么原因导致！我使用mpvue框架编写小程序，导入sdk后微信开发工具运行后台报错，信息如下：

### ISSUE THREAD

**Issue by jeffrey1995** [bmob/bmob-WeApp-sdk#9]
```
sdk uncaught third Error 
 _.extend is not a function 
 TypeError: _.extend is not a function
    at Object.<anonymous> (http://127.0.0.1:53731/appservice/static/js/pages/index/main.js:1227:19)
    at Object.<anonymous> (http://127.0.0.1:53731/appservice/static/js/pages/index/main.js:7401:16)
    at Object._ (http://127.0.0.1:53731/appservice/static/js/pages/index/main.js:7407:12)
    at __webpack_require__ (http://127.0.0.1:53731/appservice/static/js/manifest.js:71:31)
    at Object._ (http://127.0.0.1:53731/appservice/static/js/pages/index/main.js:108:80)
    at __webpack_require__ (http://127.0.0.1:53731/appservice/static/js/manifest.js:71:31)
    at Object._ (http://127.0.0.1:53731/appservice/static/js/pages/index/main.js:33:128)
    at __webpack_require__ (http://127.0.0.1:53731/appservice/static/js/manifest.js:71:31)
    at Object._ (http://127.0.0.1:53731/appservice/static/js/pages/index/main.js:13:72)
    at __webpack_require__ (http://127.0.0.1:53731/appservice/static/js/manifest.js:71:31)
```

**Comment by magic007** [comment]
wepy，我测试过没任何问题,下面这个是我使用的教程。
https://www.jianshu.com/p/28a9c435ca20


为了兼容新版ES6，我们推出了新SDK ，https://github.com/bmob/hydrogen-js-sdk ， 你也可以用这个试试

**Comment by jeffrey1995** [comment]
问题解决了，谢谢！
